version: '3.8'

services:
  headlesshere:
    build: .
    container_name: headlesshere
    privileged: true
    volumes:
      - ${LOCALPATH}:/app  # Define a local mount point for the files and mount as the app folder
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=UTC
    network_mode: "bridge"
    restart: always
    stdin_open: true  
    tty: true   
