version: '3.8'

services:
  headlesshere:
    build: .
    container_name: headlesshere
    privileged: true
    volumes:
      - ${LOCALPATH}/ttn_osm.py:/app/ttn_osm.py
      - ${LOCALPATH}/ttn_osm.py:/app/ttn.py
      - ${LOCALPATH}/ttn_osm.py:/app/here.py
      - ${LOCALPATH}/ttn_osm.py:/app/gif_ttn.py
      - ${LOCALPATH}/ttn_osm.py:/app/gif_here.py   
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=UTC
      - PYTHONPATH=/usr/local/lib/python3.9/site-packages
    network_mode: "bridge"
    restart: always
    stdin_open: true  
    tty: true   
